/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 12-May-2023 3:22:53 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */
DROP DATABASE IF EXISTS JirehDB;
CREATE DATABASE JirehDB;
USE JirehDB;

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Cliente` CASCADE
;

DROP TABLE IF EXISTS `Menu` CASCADE
;

DROP TABLE IF EXISTS `Menu_detalle` CASCADE
;

DROP TABLE IF EXISTS `Menu_tipo` CASCADE
;

DROP TABLE IF EXISTS `Proveedor` CASCADE
;

DROP TABLE IF EXISTS `Restaurante` CASCADE
;

DROP TABLE IF EXISTS `Rol` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

/* Create Tables */

CREATE TABLE `Cliente`
(
	`ClienteID` INT NOT NULL AUTO_INCREMENT,
	`RestauranteID` INT NOT NULL,
	`Nombre_cliente` VARCHAR(50) NOT NULL,
	`Telefono_cliente` VARCHAR(10) NOT NULL,
	`Direccion` VARCHAR(100) NOT NULL,
	`Tipo_cliente` VARCHAR(50) NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Cliente` PRIMARY KEY (`ClienteID` ASC)
)

;

CREATE TABLE `Menu`
(
	`MenuID` INT NOT NULL AUTO_INCREMENT,
	`RestauranteID` INT NOT NULL,
	`Nombre_menu` VARCHAR(50) NOT NULL,
	`Descripcion` VARCHAR(100) NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Menu` PRIMARY KEY (`MenuID` ASC)
)

;

CREATE TABLE `Menu_detalle`
(
	`Menu_detalleID` INT NOT NULL AUTO_INCREMENT,
	`MenuID` INT NOT NULL,
	`Menu_tipoID` INT NOT NULL,
	`Nombre` VARCHAR(50) NOT NULL,
	`Descripcion` VARCHAR(100) NOT NULL,
	`Precio` FLOAT NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Menu_detalle` PRIMARY KEY (`Menu_detalleID` ASC)
)

;

CREATE TABLE `Menu_tipo`
(
	`Menu_tipoID` INT NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) NOT NULL,
	`Descripcion` VARCHAR(100) NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Menu_tipo` PRIMARY KEY (`Menu_tipoID` ASC)
)

;

CREATE TABLE `Proveedor`
(
	`ProveedorID` INT NOT NULL AUTO_INCREMENT,
	`RestauranteID` INT NOT NULL,
	`Nombre_proveedor` VARCHAR(50) NOT NULL,
	`Telefono_proveedor` VARCHAR(10) NOT NULL,
	`Correo_proveedor` VARCHAR(50) NOT NULL,
	`Descripcion` VARCHAR(100) NOT NULL,
	`Pagina_web` VARCHAR(50) NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Proveedor` PRIMARY KEY (`ProveedorID` ASC)
)

;

CREATE TABLE `Restaurante`
(
	`RestauranteID` INT NOT NULL AUTO_INCREMENT,
	`Nombre_restaurante` VARCHAR(50) NOT NULL,
	`Telefono_restaurante` VARCHAR(10) NOT NULL,
	`Correo_restaurante` VARCHAR(50) NOT NULL,
	`Direccion` VARCHAR(100) NOT NULL,
	`Numero_ruc` VARCHAR(10) NOT NULL,
	`Pagina_web` VARCHAR(50) NOT NULL,
	`Estado` INT NOT NULL,
	CONSTRAINT `PK_Restaurante` PRIMARY KEY (`RestauranteID` ASC)
)

;

CREATE TABLE `rol`
(
	`idrol` INT NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_rol` PRIMARY KEY (`idrol` ASC)
)

;

CREATE TABLE `usuario`
(
	`idusuario` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
        `apellido` VARCHAR(50) NOT NULL,
        `nombreusuario` VARCHAR(50) NOT NULL,
	`clave` VARCHAR(10) NOT NULL,
 	`fecha_creacion` DATE NOT NULL,
	`estado` INT NOT NULL,
	CONSTRAINT `PK_usuario` PRIMARY KEY (`idusuario` ASC)
)

;

CREATE TABLE `usuario_rol`
(
	`idUsuarioRol` INT NOT NULL AUTO_INCREMENT,
	`idUsuario` INT NOT NULL,
	`idRol` INT NOT NULL,
	CONSTRAINT `PK_usuario_rol` PRIMARY KEY (`idUsuarioRol` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Cliente` 
 ADD CONSTRAINT `FK_Cliente_Restaurante`
	FOREIGN KEY (`RestauranteID`) REFERENCES `Restaurante` (`RestauranteID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Menu` 
 ADD CONSTRAINT `FK_Menu_Restaurante`
	FOREIGN KEY (`RestauranteID`) REFERENCES `Restaurante` (`RestauranteID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Menu_detalle` 
 ADD CONSTRAINT `FK_Menu_detalle_Menu`
	FOREIGN KEY (`MenuID`) REFERENCES `Menu` (`MenuID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Menu_detalle` 
 ADD CONSTRAINT `FK_Menu_detalle_Menu_tipo`
	FOREIGN KEY (`Menu_tipoID`) REFERENCES `Menu_tipo` (`Menu_tipoID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Proveedor` 
 ADD CONSTRAINT `FK_Proveedor_Restaurante`
	FOREIGN KEY (`RestauranteID`) REFERENCES `Restaurante` (`RestauranteID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `usuario_rol` 
 ADD CONSTRAINT `FK_Usuario_Rol`
	FOREIGN KEY (`idRol`) REFERENCES `rol` (`idrol`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `usuario_rol` 
 ADD CONSTRAINT `FK_Rol_Usuario`
	FOREIGN KEY (`idUsuario`) REFERENCES `usuario` (`idusuario`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 

/* ------------VISTAS---------------------------------------- */
CREATE VIEW v_usuario_rol AS
SELECT ur.idUsuarioRol, u.nombre, u.apellido, u.nombreusuario, r.descripcion
from usuario u
join usuario_rol ur on u.idusuario = ur.idUsuario 
join rol r on r.idrol = ur.idRol

/* ------------INSERTS---------------------------------------- */
INSERT INTO `jirehdb`.`rol` (`descripcion`) VALUES ('ADMIN');
INSERT INTO `jirehdb`.`rol` (`descripcion`) VALUES ('INVITADO');
INSERT INTO `jirehdb`.`rol` (`descripcion`) VALUES ('NOOB');
