# Form implementation generated from reading ui file 'vw_frmMenuTipo.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vw_menuTipo(object):
    def setupUi(self, vw_menuTipo):
        vw_menuTipo.setObjectName("vw_menuTipo")
        vw_menuTipo.resize(963, 750)
        self.centralwidget = QtWidgets.QWidget(parent=vw_menuTipo)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 931, 271))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(90, 60, 31, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 81, 17))
        self.label_3.setObjectName("label_3")
        self.txt_idMenuTip = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_idMenuTip.setGeometry(QtCore.QRect(130, 50, 291, 25))
        self.txt_idMenuTip.setObjectName("txt_idMenuTip")
        self.txt_nombreMenuTip = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_nombreMenuTip.setGeometry(QtCore.QRect(130, 90, 291, 25))
        self.txt_nombreMenuTip.setObjectName("txt_nombreMenuTip")
        self.txt_descMenuTip = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_descMenuTip.setGeometry(QtCore.QRect(130, 130, 291, 25))
        self.txt_descMenuTip.setObjectName("txt_descMenuTip")
        self.btn_nuevoMenuTIp = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_nuevoMenuTIp.setGeometry(QtCore.QRect(540, 50, 101, 41))
        self.btn_nuevoMenuTIp.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:green;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/agregar-documento.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nuevoMenuTIp.setIcon(icon)
        self.btn_nuevoMenuTIp.setObjectName("btn_nuevoMenuTIp")
        self.btn_guardarMenuTip = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_guardarMenuTip.setGeometry(QtCore.QRect(540, 100, 101, 41))
        self.btn_guardarMenuTip.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:green;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/flecha-de-circulo-de-disquete-a-la-derecha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_guardarMenuTip.setIcon(icon1)
        self.btn_guardarMenuTip.setObjectName("btn_guardarMenuTip")
        self.btn_editarMenuTip = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_editarMenuTip.setGeometry(QtCore.QRect(540, 140, 101, 41))
        self.btn_editarMenuTip.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:yellow;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_editarMenuTip.setIcon(icon2)
        self.btn_editarMenuTip.setObjectName("btn_editarMenuTip")
        self.btn_eliminarMenuTip = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_eliminarMenuTip.setGeometry(QtCore.QRect(540, 180, 101, 41))
        self.btn_eliminarMenuTip.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/eliminar-documento.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eliminarMenuTip.setIcon(icon3)
        self.btn_eliminarMenuTip.setObjectName("btn_eliminarMenuTip")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 310, 931, 411))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.jtable_menuTipo = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.jtable_menuTipo.setGeometry(QtCore.QRect(20, 20, 641, 281))
        self.jtable_menuTipo.setObjectName("jtable_menuTipo")
        self.jtable_menuTipo.setColumnCount(3)
        self.jtable_menuTipo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_menuTipo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_menuTipo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_menuTipo.setHorizontalHeaderItem(2, item)
        vw_menuTipo.setCentralWidget(self.centralwidget)

        self.retranslateUi(vw_menuTipo)
        QtCore.QMetaObject.connectSlotsByName(vw_menuTipo)

    def retranslateUi(self, vw_menuTipo):
        _translate = QtCore.QCoreApplication.translate
        vw_menuTipo.setWindowTitle(_translate("vw_menuTipo", "Tipos de Menu"))
        self.label.setText(_translate("vw_menuTipo", "ID"))
        self.label_2.setText(_translate("vw_menuTipo", "Nombre"))
        self.label_3.setText(_translate("vw_menuTipo", "Descripcion"))
        self.btn_nuevoMenuTIp.setText(_translate("vw_menuTipo", "Nuevo"))
        self.btn_guardarMenuTip.setText(_translate("vw_menuTipo", "Guardar"))
        self.btn_editarMenuTip.setText(_translate("vw_menuTipo", "Editar"))
        self.btn_eliminarMenuTip.setText(_translate("vw_menuTipo", "Eliminar"))
        item = self.jtable_menuTipo.horizontalHeaderItem(0)
        item.setText(_translate("vw_menuTipo", "ID"))
        item = self.jtable_menuTipo.horizontalHeaderItem(1)
        item.setText(_translate("vw_menuTipo", "Nombre"))
        item = self.jtable_menuTipo.horizontalHeaderItem(2)
        item.setText(_translate("vw_menuTipo", "Descripcion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vw_menuTipo = QtWidgets.QMainWindow()
    ui = Ui_vw_menuTipo()
    ui.setupUi(vw_menuTipo)
    vw_menuTipo.show()
    sys.exit(app.exec())
