# Form implementation generated from reading ui file 'vw_FrmMenuDetalle.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vw_menuDetalle(object):
    def setupUi(self, vw_menuDetalle):
        vw_menuDetalle.setObjectName("vw_menuDetalle")
        vw_menuDetalle.resize(961, 747)
        self.centralwidget = QtWidgets.QWidget(parent=vw_menuDetalle)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 941, 301))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 50, 121, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(140, 90, 41, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(120, 170, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(90, 210, 91, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(130, 250, 51, 17))
        self.label_6.setObjectName("label_6")
        self.txt_idMenuDet = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_idMenuDet.setGeometry(QtCore.QRect(190, 40, 291, 25))
        self.txt_idMenuDet.setObjectName("txt_idMenuDet")
        self.cmb_menuDetalle = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_menuDetalle.setGeometry(QtCore.QRect(190, 80, 291, 25))
        self.cmb_menuDetalle.setObjectName("cmb_menuDetalle")
        self.cmb_MenutipoDet = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_MenutipoDet.setGeometry(QtCore.QRect(190, 120, 291, 25))
        self.cmb_MenutipoDet.setObjectName("cmb_MenutipoDet")
        self.txt_nombreMenuDet = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_nombreMenuDet.setGeometry(QtCore.QRect(190, 160, 291, 25))
        self.txt_nombreMenuDet.setObjectName("txt_nombreMenuDet")
        self.txt_descMenuDet = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_descMenuDet.setGeometry(QtCore.QRect(190, 200, 291, 25))
        self.txt_descMenuDet.setObjectName("txt_descMenuDet")
        self.txt_precioMenuDet = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_precioMenuDet.setGeometry(QtCore.QRect(190, 240, 291, 25))
        self.txt_precioMenuDet.setObjectName("txt_precioMenuDet")
        self.btn_nuevoMenuDet = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_nuevoMenuDet.setGeometry(QtCore.QRect(590, 60, 101, 41))
        self.btn_nuevoMenuDet.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:green;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/agregar-documento.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nuevoMenuDet.setIcon(icon)
        self.btn_nuevoMenuDet.setObjectName("btn_nuevoMenuDet")
        self.btn_guardarMenuDet = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_guardarMenuDet.setGeometry(QtCore.QRect(590, 110, 101, 41))
        self.btn_guardarMenuDet.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:green;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/flecha-de-circulo-de-disquete-a-la-derecha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_guardarMenuDet.setIcon(icon1)
        self.btn_guardarMenuDet.setObjectName("btn_guardarMenuDet")
        self.btn_editarMenuDet = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_editarMenuDet.setGeometry(QtCore.QRect(590, 150, 101, 41))
        self.btn_editarMenuDet.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:yellow;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_editarMenuDet.setIcon(icon2)
        self.btn_editarMenuDet.setObjectName("btn_editarMenuDet")
        self.btn_eliminarMenuDet = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_eliminarMenuDet.setGeometry(QtCore.QRect(600, 200, 101, 41))
        self.btn_eliminarMenuDet.setStyleSheet("QFrame{\n"
"background-color:#aa5ff;\n"
"}\n"
"QPushButton{\n"
"background-color:#aa5ff;\n"
"border-top-left:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:red;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Descargas/CRUD Iconos-20230506T130125Z-001/CRUD Iconos/eliminar-documento.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eliminarMenuDet.setIcon(icon3)
        self.btn_eliminarMenuDet.setObjectName("btn_eliminarMenuDet")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 941, 411))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.jtable_MenuDet = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.jtable_MenuDet.setGeometry(QtCore.QRect(30, 20, 831, 331))
        self.jtable_MenuDet.setObjectName("jtable_MenuDet")
        self.jtable_MenuDet.setColumnCount(6)
        self.jtable_MenuDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.jtable_MenuDet.setHorizontalHeaderItem(5, item)
        vw_menuDetalle.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=vw_menuDetalle)
        self.statusbar.setObjectName("statusbar")
        vw_menuDetalle.setStatusBar(self.statusbar)

        self.retranslateUi(vw_menuDetalle)
        QtCore.QMetaObject.connectSlotsByName(vw_menuDetalle)

    def retranslateUi(self, vw_menuDetalle):
        _translate = QtCore.QCoreApplication.translate
        vw_menuDetalle.setWindowTitle(_translate("vw_menuDetalle", "Menu detalles"))
        self.label.setText(_translate("vw_menuDetalle", "ID_Menu Detalle"))
        self.label_2.setText(_translate("vw_menuDetalle", "Menu"))
        self.label_3.setText(_translate("vw_menuDetalle", "Menu Tipo"))
        self.label_4.setText(_translate("vw_menuDetalle", "Nombre"))
        self.label_5.setText(_translate("vw_menuDetalle", "Descripcion"))
        self.label_6.setText(_translate("vw_menuDetalle", "Precio"))
        self.btn_nuevoMenuDet.setText(_translate("vw_menuDetalle", "Nuevo"))
        self.btn_guardarMenuDet.setText(_translate("vw_menuDetalle", "Guardar"))
        self.btn_editarMenuDet.setText(_translate("vw_menuDetalle", "Editar"))
        self.btn_eliminarMenuDet.setText(_translate("vw_menuDetalle", "Eliminar"))
        item = self.jtable_MenuDet.horizontalHeaderItem(0)
        item.setText(_translate("vw_menuDetalle", "Id_Menu Detalle"))
        item = self.jtable_MenuDet.horizontalHeaderItem(1)
        item.setText(_translate("vw_menuDetalle", "Menu"))
        item = self.jtable_MenuDet.horizontalHeaderItem(2)
        item.setText(_translate("vw_menuDetalle", "MenuTipo"))
        item = self.jtable_MenuDet.horizontalHeaderItem(3)
        item.setText(_translate("vw_menuDetalle", "Nombre"))
        item = self.jtable_MenuDet.horizontalHeaderItem(4)
        item.setText(_translate("vw_menuDetalle", "Descripcion"))
        item = self.jtable_MenuDet.horizontalHeaderItem(5)
        item.setText(_translate("vw_menuDetalle", "Precio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vw_menuDetalle = QtWidgets.QMainWindow()
    ui = Ui_vw_menuDetalle()
    ui.setupUi(vw_menuDetalle)
    vw_menuDetalle.show()
    sys.exit(app.exec())
